[package]
name = "vpg-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
base64 = "0.22.1"
font8x8 = "0.3.1"
image = { version = "0.25.8", default-features = false, features = ["jpeg", "png"] }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
time.workspace = true

[lints]
workspace = true
